export type PlayerStatKey =
  | 'goals'
  | 'penaltyGoals'
  | 'missedPenalties'
  | 'mvps'
  | 'penaltiesSaved'
  | 'forcedPenaltyMisses'
  | 'shootoutPenaltiesSaved'
  | 'shootoutGoals'
  | 'shootoutMissedPenalties'
  | 'shootoutForcedPenaltyMisses'
  | 'cleanSheets'
  | 'assists'
  | 'yellowCards'
  | 'redCards';
