export const RUM_PAGES = [
  '/',
  '/login',
  '/auth/callback',
  '/pools',
  '/pools/:id',
  '/pools/:id/accept',
  '/pools/:id/accept-request/:id',
  '/pools/:id/admin',
  '/pools/:id/admin/final',
  '/pools/:id/admin/groups',
  '/pools/:id/admin/players',
  '/pools/:id/admin/settings',
  '/pools/:id/final',
  '/pools/:id/groups',
  '/pools/:id/players',
  '/pools/:id/ranking',
  '/admin',
  '/admin/final',
  '/admin/groups',
  '/admin/players',
] as const;
