export type TournamentRosterPosition = 'goalkeeper' | 'defender' | 'midfielder' | 'forward';

export type TournamentRoster = {
  teamName: string;
  players: Record<TournamentRosterPosition, readonly string[]>;
};

// Official FIFA World Cup 2026 squad list, version 1, published June 6, 2026.
function roster(
  teamName: string,
  goalkeepers: readonly string[],
  defenders: readonly string[],
  midfielders: readonly string[],
  forwards: readonly string[]
): TournamentRoster {
  return {
    teamName,
    players: {
      goalkeeper: goalkeepers,
      defender: defenders,
      midfielder: midfielders,
      forward: forwards,
    },
  };
}

export const WORLD_CUP_2026_ROSTERS: readonly TournamentRoster[] = [
  // Group A
  roster(
    'México',
    ['Raúl Rangel', 'Carlos Acevedo', 'Guillermo Ochoa'],
    [
      'Jorge Sánchez',
      'César Montes',
      'Edson Álvarez',
      'Johan Vasquez',
      'Israel Reyes',
      'Mateo Chávez',
      'Jesús Gallardo',
    ],
    [
      'Erik Lira',
      'Luis Romo',
      'Álvaro Fidalgo',
      'Orbelín Pineda',
      'Obed Vargas',
      'Gilberto Mora',
      'Luis Chávez',
      'Brian Gutiérrez',
    ],
    [
      'Raúl Jiménez',
      'Alexis Vega',
      'Santiago Giménez',
      'Armando González',
      'Julián Quiñones',
      'César Huerta',
      'Guillermo Martínez',
      'Roberto Alvarado',
    ]
  ),
  roster(
    'Sudáfrica',
    ['Ronwen Williams', 'Sipho Chaine', 'Ricardo Goss'],
    [
      'Thabang Matuludi',
      'Khulumani Ndamane',
      'Aubrey Modiba',
      'Mbekezeli Mbokazi',
      'Samukele Kabini',
      'Nkosinathi Sibisi',
      'Khuliso Mudau',
      'Ime Okon',
      'Olwethu Makhanya',
      'Bradley Cross',
    ],
    ['Teboho Mokoena', 'Thalente Mbatha', 'Themba Zwane', 'Sphephelo Sithole', 'Jayden Adams'],
    [
      'Oswin Appollis',
      'Tshepang Moremi',
      'Lyle Foster',
      'Relebohile Mofokeng',
      'Thapelo Maseko',
      'Iqraam Rayners',
      'Evidence Makgopa',
      'Kamogelo Sebelebele',
    ]
  ),
  roster(
    'República de Corea',
    ['Seung-gyu Kim', 'Bum-keun Song', 'Hyeon-woo Jo'],
    [
      'Han-beom Lee',
      'Min-jae Kim',
      'Tae-hyeon Kim',
      'Tae-seok Lee',
      'Wije Cho',
      'Moon-hwan Kim',
      'Jin-seob Park',
      'Young-woo Seol',
      'Jens Castrop',
    ],
    [
      'Ki-hyuk Lee',
      'In-beom Hwang',
      'Seung-ho Paik',
      'Jae-sung Lee',
      'Hee-chan Hwang',
      'Jun-ho Bae',
      'Kang-in Lee',
      'Hyun-jun Yang',
      'Jin-gyu Kim',
      'Ji-sung Eom',
      'Dong-gyeong Lee',
    ],
    ['Heung-min Son', 'Gue-sung Cho', 'Hyeon-gyu Oh']
  ),
  roster(
    'República Checa',
    ['Matěj Kovář', 'Jindřich Staněk', 'Lukáš Horníček'],
    [
      'David Zima',
      'Tomáš Holeš',
      'Robin Hranáč',
      'Vladimír Coufal',
      'Štěpán Chaloupek',
      'Ladislav Krejčí',
      'David Jurásek',
      'Jaroslav Zelený',
      'David Douděra',
    ],
    [
      'Vladimír Darida',
      'Lukáš Červ',
      'Lukáš Provod',
      'Michal Sadílek',
      'Tomáš Souček',
      'Alexandr Sojka',
      'Hugo Sochůrek',
    ],
    [
      'Adam Hložek',
      'Patrik Schick',
      'Jan Kuchta',
      'Mojmír Chytil',
      'Pavel Šulc',
      'Tomáš Chorý',
      'Denis Višinský',
    ]
  ),
  // Group B
  roster(
    'Canadá',
    ['Dayne St Clair', 'Maxime Crepeau', 'Owen Goodman'],
    [
      'Alistair Johnston',
      'Alfie Jones',
      'Luc de Fougerolles',
      'Joel Waterman',
      'Derek Cornelius',
      'Moise Bombito',
      'Alphonso Davies',
      'Richie Laryea',
      'Niko Sigur',
    ],
    [
      'Mathieu Choiniere',
      'Stephen Eustaquio',
      'Ismaël Koné',
      'Liam Millar',
      'Jacob Shaffelburg',
      'Jonathan Osorio',
      'Nathan Saliba',
      'Marcelo Flores',
    ],
    [
      'Cyle Larin',
      'Jonathan David',
      'Tani Oluwaseyi',
      'Tajon Buchanan',
      'Ali Ahmed',
      'Promise David',
    ]
  ),
  roster(
    'Bosnia y Herzegovina',
    ['Nikola Vasilj', 'Mladen Jurkas', 'Martin Zlomislic'],
    [
      'Nihad Mujakic',
      'Dennis Hadzikadunic',
      'Tarik Muharemovic',
      'Sead Kolasinac',
      'Amar Dedic',
      'Nikola Katic',
      'Stjepan Radeljic',
      'Nidal Celik',
    ],
    [
      'Benjamin Tahirovic',
      'Armin Gigovic',
      'Ivan Basic',
      'Ivan Sunjic',
      'Amar Memic',
      'Amir Hadziahmetovic',
      'Dzenis Burnic',
      'Ermin Mahmic',
    ],
    [
      'Samed Bazdar',
      'Ermedin Demirovic',
      'Edin Dzeko',
      'Kerim Alajbegovic',
      'Esmir Bajraktarevic',
      'Haris Tabakovic',
      'Jovo Lukic',
    ]
  ),
  roster(
    'Catar',
    ['Mahmud Abunada', 'Salah Zakaria', 'Meshaal Barsham'],
    [
      'Pedro Miguel',
      'Lucas Mendes',
      'Issa Laye',
      'Jassim Gaber',
      'Ayoub Al-Oui',
      'Homam Ahmed El-Amin',
      'Khoukhi',
      'Al-Brake',
      'Al-Hashmi Al-Hussain',
    ],
    ['Abdulaziz Hatem', 'Karim Boudiaf', 'Ahmed Al Ganehi', 'Ahmed Fathy', 'Assim Madibo'],
    [
      'Ahmed Alaa',
      'Edmilson Junior',
      'Mohammed Muntari',
      'Hassan Al-Haydos',
      'Akram Afif',
      'Yusuf Abdurisag',
      'Almoez Ali',
      'Tahsin Mohammed',
      'Mohamed Al-Mannai',
    ]
  ),
  roster(
    'Suiza',
    ['Gregor Kobel', 'Yvon Mvogo', 'Marvin Keller'],
    [
      'Miro Muheim',
      'Silvan Widmer',
      'Nico Elvedi',
      'Manuel Akanji',
      'Ricardo Rodríguez',
      'Eray Cömert',
      'Aurele Amenda',
      'Luca Jaquez',
    ],
    [
      'Denis Zakaria',
      'Remo Freuler',
      'Johan Manzambi',
      'Granit Xhaka',
      'Ardon Jashari',
      'Djibril Sow',
      'Michel Aebischer',
      'Fabian Rieder',
    ],
    [
      'Breel Embolo',
      'Dan Ndoye',
      'Christian Fassnacht',
      'Rubén Vargas',
      'Noah Okafor',
      'Zeki Amdouni',
      'Cedric Itten',
    ]
  ),
  // Group C
  roster(
    'Brasil',
    ['Alisson', 'Weverton', 'Éderson'],
    [
      'Gabriel Magalhaes',
      'Marquinhos',
      'Álex Sandro',
      'Danilo',
      'Bremer',
      'Léo Pereira',
      'Douglas Santos',
      'Ibañez',
    ],
    ['Casemiro', 'Bruno Guimares', 'Fabinho', 'Danilo', 'Lucas Paquetá', 'Éderson Silva'],
    [
      'Vinícius',
      'Matheus Cunha',
      'Neymar',
      'Raphinha',
      'Endrick',
      'Luiz Henrique',
      'Gabriel Martinelli',
      'Igor Thiago',
      'Rayan',
    ]
  ),
  roster(
    'Marruecos',
    ['Yassine Bounou', 'Munir El Kajoui', 'Ahmed Reda Tagnaouti'],
    [
      'Achraf Hakimi',
      'Noussair Mazraoui',
      'Nayef Aguerd',
      'Zakaria El Ouahdi',
      'Issa Diop',
      'Chadi Riad',
      'Youssef Belammari',
      'Redouane Halhal',
      'Anass Salah-Eddine',
    ],
    [
      'Sofyan Amrabat',
      'Ayyoub Bouaddi',
      'Chemsdine Talbi',
      'Azzedine Ounahi',
      'Ismael Saibari',
      'Samir El Mourabet',
      'Yassine Gessime',
      'Bilal El Khannouss',
      'Neil El Aynaoui',
    ],
    [
      'Soufiane Rahimi',
      'Brahim Díaz',
      'Abdessamad Ezzalzouli',
      'Ayoub El Kaabi',
      'Ayoube Amaimouni',
    ]
  ),
  roster(
    'Haití',
    ['Johnny Placide', 'Alexandre Pierre', 'Josue Duverger'],
    [
      'Carlens Arcus',
      'Keeto Thermoncy',
      'Ricardo Ade',
      'Hannes Delcroix',
      'Martin Experience',
      'Markhus Lacroix',
      'Jean-Kevin Duverne',
      'Wilguens Pauguain',
    ],
    [
      'Carl-Fred Sainthé',
      'Jean-Ricner Bellegarde',
      'Leverton Pierre',
      'Jean-Jacques Danley',
      'Dominique Simon',
      'Pierre Woodenski',
    ],
    [
      'Derrick Etienne',
      'Duckens Nazon',
      'Louicius Deedson',
      'Ruben Providence',
      'Lenny Joseph',
      'Wilson Isidor',
      'Yassin Fortune',
      'Frantzdy Pierrot',
      'Josue Casimir',
    ]
  ),
  roster(
    'Escocia',
    ['Angus Gunn', 'Liam Kelly', 'Craig Gordon'],
    [
      'Aaron Hickey',
      'Andy Robertson',
      'Grant Hanley',
      'Kieran Tierney',
      'Jack Hendry',
      'John Souttar',
      'Dominic Hyam',
      'Nathan Patterson',
      'Anthony Ralston',
      'Scott McKenna',
    ],
    [
      'Scott McTominay',
      'John McGinn',
      'Tyler Fletcher',
      'Ryan Christie',
      'Lewis Ferguson',
      'Kenny McLean',
    ],
    [
      'Lyndon Dykes',
      'Che Adams',
      'Ross Stewart',
      'Ben Gannon-Doak',
      'George Hirst',
      'Lawrence Shankland',
      'Findlay Curtis',
    ]
  ),
  // Group D
  roster(
    'Estados Unidos',
    ['Matt Turner', 'Matt Freese', 'Chris Brady'],
    [
      'Sergiño Dest',
      'Chris Richards',
      'Antonee Robinson',
      'Auston Trusty',
      'Miles Robinson',
      'Tim Ream',
      'Alex Freeman',
      'Max Arfsten',
      'Mark McKenzie',
      'Joe Scally',
    ],
    [
      'Tyler Adams',
      'Gio Reyna',
      'Weston McKennie',
      'Sebastian Berhalter',
      'Cristian Roldan',
      'Malik Tillman',
    ],
    [
      'Ricardo Pepi',
      'Christian Pulisic',
      'Brenden Aaronson',
      'Haji Wright',
      'Folarin Balogun',
      'Tim Weah',
      'Alejandro Zendejas',
    ]
  ),
  roster(
    'Paraguay',
    ['Roberto Junior Fernández', 'Orlando Gill', 'Gastón Oliveira'],
    [
      'Gustavo Velázquez',
      'Omar Alderete',
      'Juan Cáceres',
      'Fabián Balbuena',
      'Junior Alonso',
      'José Canale',
      'Gustavo Gómez',
      'Alexandre Maidana',
    ],
    [
      'Ramón Sosa',
      'Diego Gómez',
      'Miguel Almirón',
      'Mauricio Magalhaes',
      'Andrés Cubas',
      'Damián Bobadilla',
      'Braian Ojeda',
      'Matías Galarza',
      'Gustavo Caballero',
    ],
    [
      'Antonio Sanabria',
      'Alejandro Romero Gamarra',
      'Álex Arce',
      'Julio Enciso',
      'Gabriel Ávalos',
      'Isidro Pitta',
    ]
  ),
  roster(
    'Australia',
    ['Mat Ryan', 'Paul Izzo', 'Patrick Beach'],
    [
      'Milos Degenek',
      'Alessandro Circati',
      'Jacob Italiano',
      'Jordan Bos',
      'Jason Geria',
      'Kai Trewin',
      'Aziz Behich',
      'Harry Souttar',
      'Cameron Burgess',
      'Lucas Herrington',
    ],
    ['Connor Metcalfe', "Aiden O'Neill", 'Cameron Devlin', 'Jackson Irvine', 'Paul Okon-Engstler'],
    [
      'Mathew Leckie',
      'Mohamed Toure',
      'Ajdin Hrustic',
      'Awer Mabil',
      'Nestory Irankunda',
      'Cristian Volpato',
      'Nishan Velupillay',
      'Tete Yengi',
    ]
  ),
  roster(
    'Turquía',
    ['Mert Gunok', 'Altay Bayindir', 'Ugurcan Cakir'],
    [
      'Zeki Celik',
      'Merih Demiral',
      'Caglar Soyuncu',
      'Eren Elmali',
      'Abdulkerim Bardakci',
      'Ozan Kabak',
      'Mert Muldur',
      'Ferdi Kadioglu',
      'Samet Akaydin',
    ],
    ['Salih Özcan', 'Orkun Kokcu', 'Hakan Calhanoglu', 'Ismail Yuksek', 'Kaan Ayhan'],
    [
      'Kerem Akturkoglu',
      'Arda Güler',
      'Deniz Gul',
      'Kenan Yildiz',
      'Irfan Can Kahveci',
      'Yunus Akgun',
      'Baris Alper Yilmaz',
      'Oguz Aydin',
      'Can Uzun',
    ]
  ),
  // Group E
  roster(
    'Alemania',
    ['Manuel Neuer', 'Oliver Baumann', 'Alexander Nübel'],
    [
      'Antonio Rüdiger',
      'Waldemar Anton',
      'Jonathan Tah',
      'Joshua Kimmich',
      'Nico Schlotterbeck',
      'Nathaniel Brown',
      'David Raum',
      'Malick Thiaw',
    ],
    [
      'Aleksander Pavlovic',
      'Leon Goretzka',
      'Jamie Leweling',
      'Jamal Musiala',
      'Pascal Groß',
      'Angelo Stiller',
      'Florian Wirtz',
      'Leroy Sané',
      'Nadiem Amiri',
      'Felix Nmecha',
      'Lennart Karl',
    ],
    ['Kai Havertz', 'Nick Woltemade', 'Maxi Beier', 'Deniz Undav']
  ),
  roster(
    'Curazao',
    ['Eloy Room', 'Tyrick Bodak', 'Trevor Doornbusch'],
    [
      'Shurandy Sambo',
      'Jurien Gaari',
      'Roshon Van Eijma',
      'Sherel Floranus',
      'Armando Obispo',
      'Joshua Brenet',
      'Riechedly Bazoer',
      'Deveron Fonville',
    ],
    [
      'Godfried Roemeratoe',
      'Juninho Bacuna',
      'Livano Comenencia',
      'Leandro Bacuna',
      'Ar’Jany Martha',
      'Tahith Chong',
      'Kevin Felida',
    ],
    [
      'Jurgen Locadia',
      'Jeremy Antonisse',
      'Sontje Hansen',
      'Tyrese Noslin',
      'Kenji Gorre',
      'Jearl Margaritha',
      'Brandley Kuwas',
      'Gervane Kastaneer',
    ]
  ),
  roster(
    'Costa de Marfil',
    ['Yahia Fofana', 'Mohamed Koné', 'Alban Lafont'],
    [
      'Ousmane Diomande',
      'Ghislain Konan',
      'Wilfried Singo',
      'Odilon Kossounou',
      'Cristopher Operi',
      'Guela Doué',
      'Emmanuel Agbadou',
      'Evan Ndicka',
    ],
    [
      'Jean-Mickael Seri',
      'Seko Fofana',
      'Franck Kessié',
      'Ibrahim Sangare',
      'Parfait Guiagon',
      'Christ Inao Oulai',
    ],
    [
      'Ange-Yoan Bonny',
      'Simon Adingra',
      'Yan Diomande',
      'Elye Wahi',
      'Oumar Diakite',
      'Amad Diallo',
      'Nicolás Pépé',
      'Evann Guessand',
      'Bazoumana Touré',
    ]
  ),
  roster(
    'Ecuador',
    ['Hernán Galíndez', 'Moisés Ramírez', 'Gonzalo Valle'],
    [
      'Félix Torres',
      'Piero Hincapié',
      'Joel Ordóñez',
      'Willian Pacho',
      'Pervis Estupiñán',
      'Angelo Preciado',
      'Jackson Porozo',
      'Yaimar Medina',
    ],
    [
      'Jordy Alcívar',
      'Anthony Valencia',
      'Kendry Páez',
      'Alan Minda',
      'Pedro Vite',
      'Denil Castillo',
      'Alan Franco',
      'Moisés Caicedo',
    ],
    [
      'John Yeboah',
      'Kevin Rodríguez',
      'Enner Valencia',
      'Jordy Caicedo',
      'Gonzalo Plata',
      'Nilson Angulo',
      'Jeremy Arévalo',
    ]
  ),
  // Group F
  roster(
    'Países Bajos',
    ['Bart Verbruggen', 'Robin Roefs', 'Mark Flekken'],
    [
      'Jurriën Timber',
      'Virgil van Dijk',
      'Nathan Aké',
      'Jan Paul van Hecke',
      'Mats Wieffer',
      'Micky van de Ven',
      'Denzel Dumfries',
      'Jorrel Hato',
    ],
    [
      'Marten de Roon',
      'Justin Kluivert',
      'Ryan Gravenberch',
      'Tijjani Reijnders',
      'Guus Til',
      'Teun Koopmeiners',
      'Frenkie de Jong',
      'Quinten Timber',
    ],
    [
      'Wout Weghorst',
      'Memphis Depay',
      'Cody Gakpo',
      'Noa Lang',
      'Donyell Malen',
      'Brian Brobbey',
      'Crysencio Summerville',
    ]
  ),
  roster(
    'Japón',
    ['Zion Suzuki', 'Keisuke Osako', 'Tomoki Hayakawa'],
    [
      'Yukinari Sugawara',
      'Shogo Taniguchi',
      'Ko Itakura',
      'Yuto Nagatomo',
      'Tsuyoshi Watanabe',
      'Ayumu Seko',
      'Hiroki Ito',
      'Takehiro Tomiyasu',
      'Junnosuke Suzuki',
    ],
    [
      'Wataru Endo',
      'Ao Tanaka',
      'Takefusa Kubo',
      'Ritsu Doan',
      'Daizen Maeda',
      'Keito Nakamura',
      'Junya Ito',
      'Daichi Kamada',
      'Yuito Suzuki',
      'Kaishu Sano',
    ],
    ['Keisuke Goto', 'Ayase Ueda', 'Koki Ogawa', 'Kento Shiogai']
  ),
  roster(
    'Suecia',
    ['Jacob Widell Zetterstrom', 'Viktor Johansson', 'Kristoffer Nordfeldt'],
    [
      'Gustaf Lagerbielke',
      'Victor Lindelof',
      'Isak Hien',
      'Gabriel Gudmundsson',
      'Herman Johansson',
      'Daniel Svensson',
      'Hjalmar Ekdal',
      'Carl Starfelt',
      'Eric Smith',
      'Alexander Bernhardsson',
      'Elliot Stroud',
    ],
    [
      'Lucas Bergvall',
      'Benjamin Nygren',
      'Ken Sema',
      'Jesper Karlstrom',
      'Yasin Ayari',
      'Mattias Svanberg',
      'Besfort Zeneli',
    ],
    ['Alexander Isak', 'Anthony Elanga', 'Viktor Gyokeres', 'Gustaf Nilsson', 'Taha Ali']
  ),
  roster(
    'Túnez',
    ['Abdelmouhib Chamakh', 'Aymen Dahmen', 'Sabri Ben Hassen'],
    [
      'Ali Abdi',
      'Montassar Talbi',
      'Omar Rekik',
      'Adem Arous',
      'Dylan Bronn',
      'Mortadha Ben Ouanes',
      'Yan Valery',
      'Amine Ben Hamida',
      'Moutaz Neftati',
      'Raed Chikhaoui',
    ],
    [
      'Hannibal Mejbri',
      'Ismaël Gharbi',
      'Rani Khedira',
      'Khalil Ayari',
      'Mohamed Hadj Mahmoud',
      'Ellyes Skhri',
      'Anis Slimane',
      'Sebastian Tounekti',
    ],
    ['Elias Achouri', 'Elias Saad', 'Hazem Mastouri', 'Rayan Elloumi', 'Firas Chaouat']
  ),
  // Group G
  roster(
    'Bélgica',
    ['Thibaut Courtois', 'Senne Lammens', 'Mike Penders'],
    [
      'Zeno Debast',
      'Arthur Theate',
      'Brandon Mechele',
      'Maxim de Cuyper',
      'Thomas Meunier',
      'Koni de Winter',
      'Joaquin Seys',
      'Timothy Castagne',
      'Nathan Ngoy',
    ],
    [
      'Axel Witsel',
      'Kevin de Bruyne',
      'Youri Tielemans',
      'Diego Moreira',
      'Hans Vanaken',
      'Alexis Saelemaekers',
      'Nicolas Raskin',
      'Amadou Onana',
    ],
    [
      'Romelu Lukaku',
      'Leandro Trossard',
      'Jérémy Doku',
      'Dodi Lukébakio',
      'Charles de Ketelaere',
      'Matias Fernández-Pardo',
    ]
  ),
  roster(
    'Egipto',
    ['El Shennawy', 'Soliman', 'Shobeir', 'Mohamed Alaa'],
    [
      'Yasser Ibrahim',
      'Hany',
      'Abdelmaguid',
      'Rabia',
      'Abdelmonem',
      'Fattouh',
      'Hafez',
      'Tarek Alaa',
    ],
    ['Ashour', 'Ziko', 'Fathi', 'Lasheen', 'Dunga', 'Marwan Attia', 'Saber'],
    ['Trezeguet', 'Abdelkarim', 'Salah', 'Hassan', 'Adel', 'Marmoush', 'Zizo']
  ),
  roster(
    'RI de Irán',
    ['Alireza Beiranvand', 'Payam Niazmand', 'Seyed Hossein Hosseini'],
    [
      'Saleh Hardani',
      'Ehsan Hajsafi',
      'Shoja Khalilzadeh',
      'Milad Mohammadi',
      'Hossein Kanaani',
      'Aria Yousefi',
      'Ali Nemati',
      'Ramin Rezaeian',
      'Danial Eiri',
    ],
    [
      'Saeid Ezatolahi',
      'Alireza Jahanbakhsh',
      'Mohammad Mohebi',
      'Saman Ghoddos',
      'Rouzbeh Cheshmi',
      'Mehdi Torabi',
      'Mohammad Ghorbani',
      'Amir Mohammad Razzaghinia',
    ],
    [
      'Mehdi Taremi',
      'Mehdi Ghaedi',
      'Ali Alipour',
      'Amirhossein Hosseinzadeh',
      'Shahriar Moghanlou',
      'Dennis Eckert Dargahi',
    ]
  ),
  roster(
    'Nueva Zelanda',
    ['Max Crocombe', 'Alex Paulsen', 'Michael Woud'],
    [
      'Tim Payne',
      'Francis de Vries',
      'Tyler Bindon',
      'Michael Boxall',
      'Liberato Cacace',
      'Nando Pijnaker',
      'Finn Surman',
      'Callan Elliot',
      'Tommy Smith',
    ],
    [
      'Joe Bell',
      'Matt Garbett',
      'Marko Stamenic',
      'Sarpreet Singh',
      'Eli Just',
      'Alex Rufer',
      'Ben Old',
      'Callum McCowatt',
      'Ryan Thomas',
      'Lachlan Bayliss',
    ],
    ['Chris Wood', 'Kosta Barbarouses', 'Ben Waine', 'Jesse Randall']
  ),
  // Group H
  roster(
    'España',
    ['David Raya', 'Joan García', 'Unai Simón'],
    [
      'Marc Pubill',
      'Álex Grimaldo',
      'Eric García',
      'Marcos Llorente',
      'Pedro Porro',
      'Aymeric Laporte',
      'Pau Cubarsí',
      'Marc Cucurella',
    ],
    [
      'Mikel Merino',
      'Fabián Ruiz',
      'Gavi',
      'Álex Baena',
      'Rodri Hernández',
      'Martín Zubimendi',
      'Pedri González',
    ],
    [
      'Ferran Torres',
      'Dani Olmo',
      'Yeremy Pino',
      'Nico Williams',
      'Lamine Yamal',
      'Mikel Oyarzábal',
      'Víctor Muñoz',
      'Borja Iglesias',
    ]
  ),
  roster(
    'Cabo Verde',
    ['Vozinha', 'Marcos da Rosa', 'Carlos Santos'],
    [
      'Ianique Tavares "Stopira"',
      'Edilson Borges "Diney"',
      'Roberto Lopes "Pico"',
      'Logan Costa',
      'Sidny Cabral',
      'Steven Moreira',
      'Wagner Pina',
      'Kelvin Pires',
    ],
    [
      'Kevin Pina',
      'Jovane Cabral',
      'João Paulo Fernandes',
      'Jamiro Monteiro',
      'Garry Rodrigues',
      'Deroy Duarte',
      'Laros Duarte',
      'Yannick Semedo',
      'Willy Semedo',
      'Telmo Arcanjo',
      'Nuno da Costa',
      'Hélio Varela',
    ],
    ['Gilson Benchimol', 'Dailon Livramento', 'Rayan Mendes']
  ),
  roster(
    'Arabia Saudí',
    ['Nawaf Al-Aqidi', 'Mohammed Al-Owais', 'Ahmed Al-Kassar'],
    [
      'Ali Majrashi',
      'Ali Lajami',
      'Abdulelah Al-Amri',
      'Hassan Al-Tambakti',
      'Saud Abdulhamid',
      'Nawaf Boushal',
      'Hassan Kadesh',
      'Moteb Al-Harbi',
      'Jehad Thakri',
      'Mohammed Abu Al-Shamat',
    ],
    [
      'Nasser Al-Dawsari',
      'Musab Al-Juwayr',
      'Abdullah Al-Khaibari',
      'Ziyad Al-Johani',
      'Alaa Al-Hajji',
      'Mohamed Kanno',
    ],
    [
      'Ayman Yahya',
      'Firas Al-Buraikan',
      'Salem Al-Dawsari',
      'Saleh Al-Shehri',
      'Khalid Al-Ghannam',
      'Abdullah Al-Hamdan',
      'Sultan Mandash',
    ]
  ),
  roster(
    'Uruguay',
    ['Sergio Rochet', 'Santiago Mele', 'Fernando Muslera'],
    [
      'José María Giménez',
      'Sebastián Cáceres',
      'Ronald Araujo',
      'Guillermo Varela',
      'Mathías Olivera',
      'Matías Viña',
      'Santiago Bueno',
    ],
    [
      'Manuel Ugarte',
      'Rodrigo Bentancur',
      'Nicolás de la Cruz',
      'Fede Valverde',
      'Giorgian de Arrascaeta',
      'Agustín Canobbio',
      'Emiliano Martínez',
      'Maximiliano Araujo',
      'Joaquín Piquerez',
      'Juan Manuel Sanabria',
      'Rodrigo Zalazar',
    ],
    ['Darwin Núñez', 'Facundo Pellistri', 'Brian Rodríguez', 'Rodrigo Aguirre', 'Fede Viñas']
  ),
  // Group I
  roster(
    'Francia',
    ['Brice Samba', 'Mike Maignan', 'Robin Risser'],
    [
      'Malo Gusto',
      'Lucas Digne',
      'Dayot Upamecano',
      'Jules Koundé',
      'Ibrahima Konaté',
      'William Saliba',
      'Théo Hernández',
      'Lucas Hernández',
      'Maxence Lacroix',
    ],
    [
      'Manu Koné',
      'Aurélien Tchouaméni',
      "N'Golo Kanté",
      'Adrien Rabiot',
      'Warren Zaïre-Emery',
      'Rayan Cherki',
      'Maghnes Akliouche',
    ],
    [
      'Ousmane Dembélé',
      'Marcus Thuram',
      'Kylian Mbappé',
      'Michael Olise',
      'Bradley Barcola',
      'Désiré Doué',
      'Jean-Philippe Mateta',
    ]
  ),
  roster(
    'Senegal',
    ['Yehvann Diouf', 'Édouard Mendy', 'Mory Diaw'],
    [
      'Mamadou Sarr',
      'Kalidou Koulibaly',
      'Abdoulaye Seck',
      'Ismail Jakobs',
      'Krépin Diatta',
      'Moussa Niakhaté',
      'Antoine Mendy',
      'El-Hadji Malick Diouf',
    ],
    [
      'Idrissa Gana Gueye',
      'Pathé Ciss',
      'Lamine Camara',
      'Pape Matar Sarr',
      'Habib Diarra',
      'Bara Ndiaye',
      'Pape Alassane Gueye',
    ],
    [
      'Assane Diao',
      'Bamba Dieng',
      'Sadio Mané',
      'Nicolas Jackson',
      'Chérif Ndiaye',
      'Iliman Ndiaye',
      'Ismaila Sarr',
      'Ibrahim Mbaye',
    ]
  ),
  roster(
    'Irak',
    ['Fahad Talib', 'Jalal Hassan', 'Ahmed Basil'],
    [
      'Rebin Ghareeb',
      'Hussein Ali',
      'Zaid Tahseen',
      'Akam Hashim',
      'Manaf Younis',
      'Ahmed Yahya',
      'Merchas Doski',
      'Mustafa Saadoon',
      'Frans Putros',
    ],
    [
      'Youssef Amyn',
      'Ibrahim Bayesh',
      'Zidane Iqbal',
      'Amir Al-Ammari',
      'Kevin Yakob',
      'Aimar Sher',
      'Zaid Ismail',
    ],
    [
      'Ali Al-Hamadi',
      "Mohanad 'Meme' Ali",
      'Ahmed Qasem',
      'Ali Yousif',
      'Ali Jassim',
      'Aymen Hussein',
      'Marko Farji',
    ]
  ),
  roster(
    'Noruega',
    ['Orjan Nyland', 'Sander Tangvik', 'Egil Selvik'],
    [
      'Kristoffer Ajer',
      'Leo Skiri Ostigard',
      'David Moller Wolfe',
      'Fredrik Bjorkan',
      'Marcus Holmgren Pedersen',
      'Torbjorn Heggem',
      'Sondre Langas',
      'Henrik Falchener',
    ],
    [
      'Morten Thorsby',
      'Patrick Berg',
      'Sander Berge',
      'Martin Odegaard',
      'Fredrik Aursnes',
      'Kristian Thorstvedt',
      'Thelo Aasgaard',
      'Andreas Schjelderup',
      'Oscar Bobb',
      'Jens Petter Hauge',
    ],
    [
      'Alexander Sorloth',
      'Erling Braut Haaland',
      'Jorgen Strand Larsen',
      'Antonio Nusa',
      'Julian Ryerson',
    ]
  ),
  // Group J
  roster(
    'Argentina',
    ['Juan Musso', 'Gerónimo Rulli', "Emiliano 'Dibu' Martínez"],
    [
      'Leonardo Balerdi',
      'Nicolás Tagliafico',
      'Gonzalo Montiel',
      'Lisandro Martínez',
      'Cristian Romero',
      'Nicolás Otamendi',
      'Facundo Medina',
      'Nahuel Molina',
    ],
    [
      'Leandro Paredes',
      'Rodrigo de Paul',
      'Valentín Barco',
      'Giovani Lo Celso',
      'Exequiel Palacios',
      'Nicolás González',
      'Alexis Mac Allister',
      'Enzo Fernández',
    ],
    [
      'Julián Álvarez',
      'Lionel Messi',
      'Thiago Almada',
      'Giuliano Simeone',
      'Nicolás Paz',
      'José Manuel López',
      'Lautaro Martínez',
    ]
  ),
  roster(
    'Argelia',
    ['Melvin Mastil', 'Oussama Benbot', 'Luca Zidane'],
    [
      'Aïssa Mandi',
      'Achref Abada',
      'Mohamed Amine Tougaï',
      'Zineddine Belaïd',
      'Jaouen Hadjam',
      'Rayan Aït-Nouri',
      'Rafik Belghali',
      'Ramy Bensebaïni',
      'Samir Chergui',
    ],
    [
      'Ramiz Zerrouki',
      'Houssem Aouar',
      'Farès Chaïbi',
      'Hicham Boudaoui',
      'Nabil Bentaleb',
      'Ibrahim Maza',
      'Yacine Titraoui',
    ],
    [
      'Riyad Mahrez',
      'Amine Gouiri',
      'Anis Hadj Moussa',
      'Nadhir Benbouali',
      'Mohamed Amine Amoura',
      'Adil Boulbina',
      'Farès Ghedjemis',
    ]
  ),
  roster(
    'Austria',
    ['Alexander Schlager', 'Florian Wiegele', 'Patrick Pentz'],
    [
      'David Affengruber',
      'Kevin Danso',
      'Stefan Posch',
      'David Alaba',
      'Philipp Lienhart',
      'Phillipp Mwene',
      'Marco Friedl',
      'Michael Svoboda',
    ],
    [
      'Xaver Schlager',
      'Nicolas Seiwald',
      'Marcel Sabitzer',
      'Florian Grillitsch',
      'Carney Chukwuemeka',
      'Romano Schmid',
      'Dejan Ljubičić',
      'Konrad Laimer',
      'Alexander Prass',
      'Paul Wanner',
      'Alessandro Schopf',
    ],
    ['Marko Arnautovic', 'Michael Gregoritsch', 'Sasa Kalajdzic', 'Patrick Wimmer']
  ),
  roster(
    'Jordania',
    ['Yazeed Abu Laila', 'Nour Bani Attiah', 'Abdullah Al Fakhouri'],
    [
      'Mohammad Abu Hashish',
      'Abdullah Nasib',
      'Hussam Abu Dahab',
      'Yazan Al-Arab',
      'Mohammed Abu Al-Nadi',
      'Saleem Obaid',
      'Saad Al-Rousan',
      'Ehsan Haddad',
      'Anas Badawi',
    ],
    [
      'Amer Jamous',
      'Nour Al-Rawabdeh',
      'Rajaei Ayed',
      'Ibrahim Saadeh',
      'Mohannad Abu Taha',
      'Nizar Al-Rashdan',
      'Mohammed Al-Daoud',
    ],
    [
      'Mohammad Abuzraiq',
      'Ali Olwan',
      'Mousa Al-Tamari',
      'Odeh Al-Fakhouri',
      'Mahmoud Al-Mardi',
      'Ibrahim Sabra',
      'Ali Azaizeh',
    ]
  ),
  // Group K
  roster(
    'Portugal',
    ['Diogo Costa', 'José Sá', 'Rui Silva'],
    [
      'Nélson Semedo',
      'Rúben Dias',
      'Tomás Araújo',
      'Diogo Dalot',
      'Renato Veiga',
      'Gonçalo Inácio',
      'Joao Cancelo',
      'Samú Costa',
      'Nuno Mendes',
    ],
    ['Matheus Nunes', 'Bruno Fernandes', 'Bernardo Silva', 'João Neves', 'Rúben Neves', 'Vitinha'],
    [
      'Cristiano Ronaldo',
      'Gonçalo Ramos',
      'João Félix',
      'Trincão',
      'Rafael Leão',
      'Pedro Neto',
      'Gonçalo Guedes',
      'Francisco Conceição',
    ]
  ),
  roster(
    'RD de Congo',
    ['Lionel Mpasi', 'Timothy Fayulu', 'Matthieu Epolo'],
    [
      'Aaron Wan-Bissaka',
      'Steve Kapuadi',
      'Axel Tuanzebe',
      'Dylan Batubinsika',
      'Joris Kayembe',
      'Chancel Mbemba',
      'Gedeon Kalulu',
      'Arthur Masuaku',
    ],
    [
      'Ngalayel Mukau',
      'Nathanael Mbuku',
      'Samuel Moutoussamy',
      'Théo Bongonda',
      'Noah Sadiki',
      'Aaron Tshibola',
      'Charles Pickel',
      'Edo Kayembe',
    ],
    [
      'Brian Cipenga',
      'Gael Kakuta',
      'Elia Meshack',
      'Cédric Bakambu',
      'Fiston Mayele',
      'Yoane Wissa',
      'Simon Banza',
    ]
  ),
  roster(
    'Uzbekistán',
    ['Utkir Yusupov', 'Abdovkih Nematov', 'Botirali Ergashev'],
    [
      'Abduqodir Khusanov',
      'Khojiakbar Alijonov',
      'Farrukh Sayfiev',
      'Rustamjon Ashurmatov',
      'Sherzos Nasrrulaev',
      'Umarbek Eshmurodov',
      'Abdulla Abdulaev',
      'Berhuz Karimov',
      'Avazbek Ylmasaliev',
      'Jakhongir Urozov',
    ],
    [
      'Akmal Mozgovoy',
      'Otakeb Shukubov',
      'Jamshid Iskanderov',
      'Odiljon Khamrobekov',
      'Jaloliddin Masharipov',
      'Oston Urunov',
      'Dostonbek Khamdamov',
      'Azizjon Ganiev',
      'Abbosek Fayzullaev',
      'Sherzod Esanov',
    ],
    ['Eldor Shomurodov', 'Azizbek Amonov', 'Igor Sergeev']
  ),
  roster(
    'Colombia',
    ['David Ospina', 'Camilo Vargas', 'Álvaro Montero'],
    [
      'Daniel Muñoz',
      'Jhon Lucumí',
      'Santiago Arias',
      'Yerry Mina',
      'Puerta',
      'Johan Mojica',
      'Wilder Ditta',
      'Deiver Machado',
      'Dávinson Sánchez',
    ],
    [
      'Kevin Castaño',
      'Richard Ríos',
      'Jorge Carrascal',
      'James Rodríguez',
      'Jhon Arias',
      'Juan Camilo Portilla',
      'Jefferson Lerma',
      'Juan Fernando Quintero',
    ],
    [
      'Luis Díaz',
      'Jhon Córdoba',
      "Juan Camilo 'Cucho' Hernández",
      'Jaminton Campaz',
      'Luis Suárez',
      'Carlos Andrés Gómez',
    ]
  ),
  // Group L
  roster(
    'Inglaterra',
    ['Jordan Pickford', 'Dean Henderson', 'James Trafford'],
    [
      'Ezri Konsa',
      "Nico O'Reilly",
      'John Stones',
      'Marc Guehi',
      'Tino Livramento',
      'Dan Burn',
      'Reece James',
      'Djed Spence',
      'Jarell Quansah',
    ],
    [
      'Declan Rice',
      'Elliot Anderson',
      'Jude Bellingham',
      'Jordan Henderson',
      'Kobbie Mainoo',
      'Morgan Rogers',
      'Eberechi Eze',
    ],
    [
      'Bukayo Saka',
      'Harry Kane',
      'Marcus Rashford',
      'Anthony Gordon',
      'Ollie Watkins',
      'Noni Madueke',
      'Ivan Toney',
    ]
  ),
  roster(
    'Croacia',
    ['Dominik Livaković', 'Ivor Pandur', 'Dominik Kotarski'],
    [
      'Josip Stanišić',
      'Marin Pongračić',
      'Joško Gvardiol',
      'Duje Ćaleta-Car',
      'Josip Šutalo',
      'Kristijan Jakić',
      'Luka Vušković',
      'Martin Erlić',
    ],
    [
      'Nikola Moro',
      'Mateo Kovačić',
      'Luka Modrić',
      'Nikola Vlašić',
      'Mario Pašalić',
      'Martin Baturina',
      'Petar Sučić',
      'Toni Fruk',
      'Luka Sučić',
    ],
    [
      'Andrej Kramarić',
      'Ante Budimir',
      'Ivan Perišić',
      'Igor Matanović',
      'Marco Pašalić',
      'Petar Musa',
    ]
  ),
  roster(
    'Ghana',
    ['Lawrence Ati-Zigi', 'Joseph Anang', 'Benjamin Asare'],
    [
      'Alidu Seidu',
      'Jonas Adjetey',
      'Abdul Mumin',
      'Gideon Mensah',
      'Baba Abdul Rahman',
      'Jerome Opoku',
      'Kojo Eppong Peprah',
      'Derrick Luckassen',
      'Marvin Senaya',
    ],
    [
      'Caleb Yirenki',
      'Thomas Partey',
      'Kwasi Sibo',
      'Antoine Semenyo',
      'Elisha Owusu',
      'Augustine Boakye',
    ],
    [
      'Abdul Fatawu Issahaku',
      'Jordan Ayew',
      'Brandon Thomas-Asante',
      'Christopher Bonsu Baah',
      'Iñaki Williams',
      'Kamaldeen Sulemana',
      'Ernest Nuamah',
      'Prince Kwabena Adu',
    ]
  ),
  roster(
    'Panamá',
    ['Luis Mejía', 'César Samudio', 'Orlando Mosquera'],
    [
      'César Blackman',
      'José Córdoba',
      'Fidel Escobar',
      'Edgardo Fariña',
      'Jiovany Ramos',
      'Carlos Harvey',
      'Eric Davis',
      'Andrés Andrade',
      'Michael Murillo',
      'Roderick Miller',
      'Jorge Gutiérrez',
    ],
    [
      'Cristian Martínez',
      'José Luis Rodríguez',
      'Adalberto Carrasquilla',
      'Ismael Díaz',
      'Yoel Bárcenas',
      'Alberto Quintero',
      'Aníbal Godoy',
      'César Yanis',
    ],
    ['Tomás Rodríguez', 'José Fajardo', 'Cecilio Waterman', 'Azarías Londoño']
  ),
];
